CREATE DATABASE IF NOT EXISTS `BookStore`;
USE `BookStore`;

CREATE TABLE IF NOT EXISTS `Books`(
	BookID INT AUTO_INCREMENT,
	ReleasedDate INT NOT NULL,
	Stock INT NOT NULL,
	Genre VARCHAR(20) NOT NULL,
	Category VARCHAR(20) NOT NULL,
	Price INT NOT NULL,
	Name VARCHAR(50) NOT NULL,
	ISBN VARCHAR(13) NOT NULL,
    PRIMARY KEY (`BookID`),
	Language VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS `Authors` (
	AuthorID INT AUTO_INCREMENT,
    Name VARCHAR(30) NOT NULL,
	PRIMARY KEY (`AuthorID`)
);

CREATE TABLE IF NOT EXISTS `AuthorBooks`(
    ABID INT(11) NOT NULL AUTO_INCREMENT,
	AuthorID INT(11) NOT NULL,
    BookID INT(11) NOT NULL,
    PRIMARY KEY(`ABID`),
    FOREIGN KEY(`AuthorID`) REFERENCES `Authors` (`AuthorID`),
    FOREIGN KEY(`BookID`) REFERENCES `Books` (`BookID`)
);

CREATE TABLE IF NOT EXISTS `Coupons`(
    CouponID INT NOT NULL AUTO_INCREMENT,
    Code VARCHAR(30) NOT NULL,
    DiscountPercent TINYINT NOT NULL,
    Expires DATETIME NOT NULL,
    PRIMARY KEY(`CouponID`)
);

CREATE TABLE IF NOT EXISTS `Cities`(
	CityID INT AUTO_INCREMENT,
	City VARCHAR(30) NOT NULL,
	ZipCode INT NOT NULL,
	PRIMARY KEY (`CityID`)
);

CREATE TABLE IF NOT EXISTS `Addresses` (
	AddressID INT AUTO_INCREMENT,
	CityID INT NOT NULL,
	StreetName VARCHAR(30) NOT NULL,
	HouseNumber VARCHAR(15) NOT NULL,
	PRIMARY KEY (`AddressID`),
	CONSTRAINT fk_city FOREIGN KEY (`CityID`) REFERENCES `Cities` (`CityID`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `Customers`(
	CustomerID INT AUTO_INCREMENT,
	AddressID INT NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Password VARCHAR(255) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`CustomerID`),
	CONSTRAINT fk_address FOREIGN KEY (`AddressID`) REFERENCES `Addresses` (`AddressID`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `Orders` (
	OrderID INT AUTO_INCREMENT,
	CustomerID INT NOT NULL,
	CouponID INT,
	TotalPrice DOUBLE NOT NULL,
	CreatedAt DateTime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`OrderID`),
	CONSTRAINT fk_customer FOREIGN KEY (`CustomerID`) REFERENCES `Customers` (`CustomerID`) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_coupon FOREIGN KEY (`CouponID`) REFERENCES `Coupons` (`CouponID`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `Orderitems` (
	OrderItemID INT AUTO_INCREMENT,
	BookID INT NOT NULL,
	OrderID INT NOT NULL,
	Price DECIMAL(10,2) NOT NULL,
	Quantity INT NOT NULL,
    PRIMARY KEY (`OrderItemID`),
	CONSTRAINT fk_book_Order FOREIGN KEY (`BookID`) REFERENCES `Books` (`BookID`) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_order FOREIGN KEY (`OrderID`) REFERENCES `Orders` (`OrderID`) ON DELETE CASCADE ON UPDATE CASCADE
);
