POST http://localhost:1000/api/v1/users/createUser
Content-Type: application/json
Origin: localhost

{
    "name": "Matt Mattson",
    "email": "mattm@tson.com",
    "password": "v1",
    "verifyPassword": "V1",
    "zipCode": "4200",
    "houseNumber": "1A",
    "streetName": "DoesNotExist",
    "phoneNumber": "12341235"
}